#!/bin/bash
#
# Vyatta Xen postinstall hook
#

set -e

: ${vyatta_prefix:=/opt/vyatta}
: ${vyatta_exec_prefix:=$vyatta_prefix}
: ${vyatta_sbindir:=${vyatta_exec_prefix}/sbin}

source ${vyatta_sbindir}/vyatta-grub.functions
source ${vyatta_sbindir}/vyatta-install-image.functions

function check_for_xen_extras ()
{
    : ${VII_POSTINSTALL_VYATTA_XEN:=false}

    local manuf=$(dmidecode -s system-manufacturer 2>/dev/null)
    local prod=$(dmidecode -s system-product-name 2>/dev/null)

    # open output to real tty
    exec 3>/dev/tty

    if [ "$manuf" = "Xen" -a "$prod" = "HVM domU" ]; then
	local response="No"
	[ "${VII_POSTINSTALL_VYATTA_XEN}" = "true" ] && response="Yes"

        echo "You are installing to a $manuf $prod virtual machine." >&3
        echo "Would you like to set up config files to prepare for the" >&3
        echo -n "conversion to PV domU? [${response}]: " >&3
        response=$(get_response "${response}" "Yes No Y N")
	if [[ ${response} == Y* ]]; then
		VII_POSTINSTALL_VYATTA_XEN=true

		# Get the root device that will hold the root filesystem
		rootdev="${VII_POSTINSTALL_VYATTA_XEN_ROOTDEV:-xvda1}"
		echo -n "Root filesystem device [${rootdev}]: " >&3
		rootdev=$(get_response_raw "${rootdev}")
		echo "Using $rootdev" >&3
	fi
    fi

    exec 3>&-

    echo "VII_POSTINSTALL_VYATTA_XEN=${VII_POSTINSTALL_VYATTA_XEN}"
    echo "VII_POSTINSTALL_VYATTA_XEN_ROOTDEV=${rootdev}"
}

function setup_xen_extras ()
{
    local root_dir=${1?Missing argument}
    local image_name=${2?Missing argument}
    local rootdev=${VII_POSTINSTALL_VYATTA_XEN_ROOTDEV?Missing root device}

    # Add symlink pointing to default image
    local xen_grub_boot_path=/boot/%%default_image

    # determine the persistent installation device or fallback to *_ROOTDEV
    local boot_path=$(what_is_mounted_on ${root_dir}/boot)
    : ${boot_path:=${VII_POSTINSTALL_VYATTA_XEN_ROOTDEV}}
    boot_path=/lib/live/mount/persistence/${boot_path##/dev/}/boot
    ln -fs $image_name ${root_dir}${boot_path}/${xen_grub_boot_path##/boot/}

    # Set up /boot/grub/menu.lst for use by pygrub
    local grub_options=$(get_default_grub_options ${xen_grub_boot_path##/boot/})
    grub_options+=" console=hvc0"

    cat >> ${root_dir}/boot/grub/menu.lst <<EOF
timeout 5

title    vyatta-virt
root     (hd0,0)
kernel   ${xen_grub_boot_path}/vmlinuz root=/dev/$rootdev ${grub_options}
initrd   ${xen_grub_boot_path}/initrd.img
EOF

    # Add console port entry for the Xen PV console
    add_console_entry hvc0 "${root_dir}${VYATTA_NEW_CFG_DIR}/config.boot" 9600
}

case "$1" in
    configure)
	check_for_xen_extras
	;;
    run)
	[ "${VII_POSTINSTALL_VYATTA_XEN}" = "true" ] && setup_xen_extras $2 $3
	;;
    *)
	fail_exit "$0: unknown command: $1"
	;;
esac

exit 0
