#!/bin/sh

set -e

pkg=vyatta-image-tools

case "${1}" in
    remove)
	dpkg-divert --package ${pkg} --quiet --remove --rename \
	    --divert /usr/sbin/update-grub.grub2-common /usr/sbin/update-grub
	;;

    purge|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)

        ;;

    *)
        echo "postrm called with unknown argument \`${1}'" >&2
        exit 1
        ;;
esac

#DEBHELPER#

exit 0
